name: Running tests

# Trigger the workflow on push and pull request to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the build environment
      # Install any dependencies (like build-essential for compiling C programs)
      - name: Set up build environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Step 3: Build and run the tests
      - name: Build and Run Tests
        run: make run_test
